### ISSUE TITLE
Update donkey to use jargon dev

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/DFC-Test-Environment#4]
upgrade donkey on de test backend service lab

**Comment by michael-conway** [comment]
donkey being built with 4.0.3.1 snapshot to match cloud browser codebase

**Comment by michael-conway** [comment]
breaks when updated...

donkey-shell.log in var/log/donkey

```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
13:41:16.489 [main] ERROR clojure-commons.config - required configuration setting donkey.metadata.base-url is empty or undefined
Exception in thread "main" clojure.lang.ExceptionInfo: throw+: {:error_code "ERR_CONFIG_INVALID"} {:error_code "ERR_CONFIG_INVALID"}
    at donkey.util.config$validate_config.invoke(config.clj:518)
    at donkey.util.config$load_config_from_file.invoke(config.clj:551)
    at donkey.core$_main.doInvoke(core.clj:253)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at donkey.core.main(Unknown Source)
Sep 24, 2015 1:41:21 PM com.mchange.v2.log.MLog <clinit>



```

**Comment by michael-conway** [comment]
need the following steps
- back up database on dfc-test-de.edc.renci.org via sqldump
- build new schema .gz file from https://github.com/DICE-UNC/DiscoveryEnvironmentBackend/tree/master/databases
- use facepalm to upgrade postgres https://github.com/DICE-UNC/DiscoveryEnvironmentBackend/tree/master/tools/facepalm for both de, jex, notif, and metadata
- build and deploy donkey and other services, including metadata
- uprade and deploy de
